/*
 * This file is generated by jOOQ.
 */
package com.ecommerce.analytics.jooq.tables.records;


import com.ecommerce.analytics.jooq.tables.OrderItems;

import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderItemsRecord extends UpdatableRecordImpl<OrderItemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.order_items.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.order_items.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.order_items.order_id</code>.
     */
    public void setOrderId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.order_items.order_id</code>.
     */
    public Integer getOrderId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.order_items.product_id</code>.
     */
    public void setProductId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.order_items.product_id</code>.
     */
    public Integer getProductId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.order_items.quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.order_items.quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.order_items.price_at_purchase</code>.
     */
    public void setPriceAtPurchase(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.order_items.price_at_purchase</code>.
     */
    public BigDecimal getPriceAtPurchase() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderItemsRecord
     */
    public OrderItemsRecord() {
        super(OrderItems.ORDER_ITEMS);
    }

    /**
     * Create a detached, initialised OrderItemsRecord
     */
    public OrderItemsRecord(Integer id, Integer orderId, Integer productId, Integer quantity, BigDecimal priceAtPurchase) {
        super(OrderItems.ORDER_ITEMS);

        setId(id);
        setOrderId(orderId);
        setProductId(productId);
        setQuantity(quantity);
        setPriceAtPurchase(priceAtPurchase);
        resetChangedOnNotNull();
    }
}
