/*
 * This file is generated by jOOQ.
 */
package com.ecommerce.analytics.jooq.tables.records;


import com.ecommerce.analytics.jooq.tables.OrderStatuses;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderStatusesRecord extends UpdatableRecordImpl<OrderStatusesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.order_statuses.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.order_statuses.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.order_statuses.status_name</code>.
     */
    public void setStatusName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.order_statuses.status_name</code>.
     */
    public String getStatusName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderStatusesRecord
     */
    public OrderStatusesRecord() {
        super(OrderStatuses.ORDER_STATUSES);
    }

    /**
     * Create a detached, initialised OrderStatusesRecord
     */
    public OrderStatusesRecord(Integer id, String statusName) {
        super(OrderStatuses.ORDER_STATUSES);

        setId(id);
        setStatusName(statusName);
        resetChangedOnNotNull();
    }
}
