/*
 * This file is generated by jOOQ.
 */
package com.ecommerce.analytics.jooq;


import com.ecommerce.analytics.jooq.tables.Customers;
import com.ecommerce.analytics.jooq.tables.OrderItems;
import com.ecommerce.analytics.jooq.tables.OrderStatuses;
import com.ecommerce.analytics.jooq.tables.Orders;
import com.ecommerce.analytics.jooq.tables.Products;
import com.ecommerce.analytics.jooq.tables.records.CustomersRecord;
import com.ecommerce.analytics.jooq.tables.records.OrderItemsRecord;
import com.ecommerce.analytics.jooq.tables.records.OrderStatusesRecord;
import com.ecommerce.analytics.jooq.tables.records.OrdersRecord;
import com.ecommerce.analytics.jooq.tables.records.ProductsRecord;

import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomersRecord> CUSTOMERS_EMAIL_KEY = Internal.createUniqueKey(Customers.CUSTOMERS, DSL.name("customers_email_key"), new TableField[] { Customers.CUSTOMERS.EMAIL }, true);
    public static final UniqueKey<CustomersRecord> CUSTOMERS_PKEY = Internal.createUniqueKey(Customers.CUSTOMERS, DSL.name("customers_pkey"), new TableField[] { Customers.CUSTOMERS.ID }, true);
    public static final UniqueKey<OrderItemsRecord> ORDER_ITEMS_PKEY = Internal.createUniqueKey(OrderItems.ORDER_ITEMS, DSL.name("order_items_pkey"), new TableField[] { OrderItems.ORDER_ITEMS.ID }, true);
    public static final UniqueKey<OrderStatusesRecord> ORDER_STATUSES_PKEY = Internal.createUniqueKey(OrderStatuses.ORDER_STATUSES, DSL.name("order_statuses_pkey"), new TableField[] { OrderStatuses.ORDER_STATUSES.ID }, true);
    public static final UniqueKey<OrderStatusesRecord> ORDER_STATUSES_STATUS_NAME_KEY = Internal.createUniqueKey(OrderStatuses.ORDER_STATUSES, DSL.name("order_statuses_status_name_key"), new TableField[] { OrderStatuses.ORDER_STATUSES.STATUS_NAME }, true);
    public static final UniqueKey<OrdersRecord> ORDERS_PKEY = Internal.createUniqueKey(Orders.ORDERS, DSL.name("orders_pkey"), new TableField[] { Orders.ORDERS.ID }, true);
    public static final UniqueKey<ProductsRecord> PRODUCTS_PKEY = Internal.createUniqueKey(Products.PRODUCTS, DSL.name("products_pkey"), new TableField[] { Products.PRODUCTS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<OrderItemsRecord, OrdersRecord> ORDER_ITEMS__FK_ORDER_ID = Internal.createForeignKey(OrderItems.ORDER_ITEMS, DSL.name("fk_order_id"), new TableField[] { OrderItems.ORDER_ITEMS.ORDER_ID }, Keys.ORDERS_PKEY, new TableField[] { Orders.ORDERS.ID }, true);
    public static final ForeignKey<OrderItemsRecord, ProductsRecord> ORDER_ITEMS__FK_PRODUCT_ID = Internal.createForeignKey(OrderItems.ORDER_ITEMS, DSL.name("fk_product_id"), new TableField[] { OrderItems.ORDER_ITEMS.PRODUCT_ID }, Keys.PRODUCTS_PKEY, new TableField[] { Products.PRODUCTS.ID }, true);
    public static final ForeignKey<OrdersRecord, CustomersRecord> ORDERS__FK_CUSTOMER_ID = Internal.createForeignKey(Orders.ORDERS, DSL.name("fk_customer_id"), new TableField[] { Orders.ORDERS.CUSTOMER_ID }, Keys.CUSTOMERS_PKEY, new TableField[] { Customers.CUSTOMERS.ID }, true);
    public static final ForeignKey<OrdersRecord, OrderStatusesRecord> ORDERS__FK_STATUS_NAME = Internal.createForeignKey(Orders.ORDERS, DSL.name("fk_status_name"), new TableField[] { Orders.ORDERS.STATUS_ID }, Keys.ORDER_STATUSES_PKEY, new TableField[] { OrderStatuses.ORDER_STATUSES.ID }, true);
}
