/*
 * This file is generated by jOOQ.
 */
package com.ecommerce.analytics.jooq;


import com.ecommerce.analytics.jooq.tables.Customers;
import com.ecommerce.analytics.jooq.tables.OrderItems;
import com.ecommerce.analytics.jooq.tables.OrderStatuses;
import com.ecommerce.analytics.jooq.tables.Orders;
import com.ecommerce.analytics.jooq.tables.Products;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.customers</code>.
     */
    public final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>public.order_items</code>.
     */
    public final OrderItems ORDER_ITEMS = OrderItems.ORDER_ITEMS;

    /**
     * The table <code>public.order_statuses</code>.
     */
    public final OrderStatuses ORDER_STATUSES = OrderStatuses.ORDER_STATUSES;

    /**
     * The table <code>public.orders</code>.
     */
    public final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.products</code>.
     */
    public final Products PRODUCTS = Products.PRODUCTS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Customers.CUSTOMERS,
            OrderItems.ORDER_ITEMS,
            OrderStatuses.ORDER_STATUSES,
            Orders.ORDERS,
            Products.PRODUCTS
        );
    }
}
