/*
 * This file is generated by jOOQ.
 */
package com.ecommerce.analytics.jooq;


import com.ecommerce.analytics.jooq.tables.Customers;
import com.ecommerce.analytics.jooq.tables.OrderItems;
import com.ecommerce.analytics.jooq.tables.OrderStatuses;
import com.ecommerce.analytics.jooq.tables.Orders;
import com.ecommerce.analytics.jooq.tables.Products;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.customers</code>.
     */
    public static final Customers CUSTOMERS = Customers.CUSTOMERS;

    /**
     * The table <code>public.order_items</code>.
     */
    public static final OrderItems ORDER_ITEMS = OrderItems.ORDER_ITEMS;

    /**
     * The table <code>public.order_statuses</code>.
     */
    public static final OrderStatuses ORDER_STATUSES = OrderStatuses.ORDER_STATUSES;

    /**
     * The table <code>public.orders</code>.
     */
    public static final Orders ORDERS = Orders.ORDERS;

    /**
     * The table <code>public.products</code>.
     */
    public static final Products PRODUCTS = Products.PRODUCTS;
}
