/*
 * This file is generated by jOOQ.
 */
package com.github.anastasiia.ecommerceanalyticsservice.jooq.tables.records;


import com.github.anastasiia.ecommerceanalyticsservice.jooq.tables.Orders;

import java.time.LocalDate;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrdersRecord extends UpdatableRecordImpl<OrdersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.orders.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.orders.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.orders.customer_id</code>.
     */
    public void setCustomerId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.orders.customer_id</code>.
     */
    public Integer getCustomerId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.orders.order_date</code>.
     */
    public void setOrderDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.orders.order_date</code>.
     */
    public LocalDate getOrderDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.orders.status_id</code>.
     */
    public void setStatusId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.orders.status_id</code>.
     */
    public Integer getStatusId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrdersRecord
     */
    public OrdersRecord() {
        super(Orders.ORDERS);
    }

    /**
     * Create a detached, initialised OrdersRecord
     */
    public OrdersRecord(Integer id, Integer customerId, LocalDate orderDate, Integer statusId) {
        super(Orders.ORDERS);

        setId(id);
        setCustomerId(customerId);
        setOrderDate(orderDate);
        setStatusId(statusId);
        resetChangedOnNotNull();
    }
}
