/*
 * This file is generated by jOOQ.
 */
package com.github.anastasiia.ecommerceanalyticsservice.jooq.tables;


import com.github.anastasiia.ecommerceanalyticsservice.jooq.Keys;
import com.github.anastasiia.ecommerceanalyticsservice.jooq.Public;
import com.github.anastasiia.ecommerceanalyticsservice.jooq.tables.Orders.OrdersPath;
import com.github.anastasiia.ecommerceanalyticsservice.jooq.tables.records.OrderStatusesRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OrderStatuses extends TableImpl<OrderStatusesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.order_statuses</code>
     */
    public static final OrderStatuses ORDER_STATUSES = new OrderStatuses();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrderStatusesRecord> getRecordType() {
        return OrderStatusesRecord.class;
    }

    /**
     * The column <code>public.order_statuses.id</code>.
     */
    public final TableField<OrderStatusesRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.order_statuses.status_name</code>.
     */
    public final TableField<OrderStatusesRecord, String> STATUS_NAME = createField(DSL.name("status_name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    private OrderStatuses(Name alias, Table<OrderStatusesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrderStatuses(Name alias, Table<OrderStatusesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.order_statuses</code> table reference
     */
    public OrderStatuses(String alias) {
        this(DSL.name(alias), ORDER_STATUSES);
    }

    /**
     * Create an aliased <code>public.order_statuses</code> table reference
     */
    public OrderStatuses(Name alias) {
        this(alias, ORDER_STATUSES);
    }

    /**
     * Create a <code>public.order_statuses</code> table reference
     */
    public OrderStatuses() {
        this(DSL.name("order_statuses"), null);
    }

    public <O extends Record> OrderStatuses(Table<O> path, ForeignKey<O, OrderStatusesRecord> childPath, InverseForeignKey<O, OrderStatusesRecord> parentPath) {
        super(path, childPath, parentPath, ORDER_STATUSES);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OrderStatusesPath extends OrderStatuses implements Path<OrderStatusesRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OrderStatusesPath(Table<O> path, ForeignKey<O, OrderStatusesRecord> childPath, InverseForeignKey<O, OrderStatusesRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OrderStatusesPath(Name alias, Table<OrderStatusesRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OrderStatusesPath as(String alias) {
            return new OrderStatusesPath(DSL.name(alias), this);
        }

        @Override
        public OrderStatusesPath as(Name alias) {
            return new OrderStatusesPath(alias, this);
        }

        @Override
        public OrderStatusesPath as(Table<?> alias) {
            return new OrderStatusesPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<OrderStatusesRecord, Integer> getIdentity() {
        return (Identity<OrderStatusesRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<OrderStatusesRecord> getPrimaryKey() {
        return Keys.ORDER_STATUSES_PKEY;
    }

    @Override
    public List<UniqueKey<OrderStatusesRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ORDER_STATUSES_STATUS_NAME_KEY);
    }

    private transient OrdersPath _orders;

    /**
     * Get the implicit to-many join path to the <code>public.orders</code>
     * table
     */
    public OrdersPath orders() {
        if (_orders == null)
            _orders = new OrdersPath(this, null, Keys.ORDERS__FK_STATUS_NAME.getInverseKey());

        return _orders;
    }

    @Override
    public OrderStatuses as(String alias) {
        return new OrderStatuses(DSL.name(alias), this);
    }

    @Override
    public OrderStatuses as(Name alias) {
        return new OrderStatuses(alias, this);
    }

    @Override
    public OrderStatuses as(Table<?> alias) {
        return new OrderStatuses(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderStatuses rename(String name) {
        return new OrderStatuses(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderStatuses rename(Name name) {
        return new OrderStatuses(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrderStatuses rename(Table<?> name) {
        return new OrderStatuses(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderStatuses where(Condition condition) {
        return new OrderStatuses(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderStatuses where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderStatuses where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderStatuses where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderStatuses where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderStatuses where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderStatuses where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrderStatuses where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderStatuses whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrderStatuses whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
